version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    privileged: true
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/variable.conf:/etc/nginx/variable.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    privileged: true
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  app:
    container_name: jajakjajak-demo
    build:
      context: .
